---


##WEBDEV

-  name: install npm
   become: yes
   become_user: root
   apt:
      name: npm
      update_cache: no

-  name: install babel and browserify
   become: yes
   become_user: root
   shell: npm install --global babel-cli browserify

-  name: install react jsx
   shell: cd "{{faex_path}}/web_ui"; npm install --save-dev babel-plugin-transform-react-jsx

-  name: install pip libraries for webdev (flask_sockets)
   become: yes
   become_user: root
   shell: pip3 install flask_sockets libsass



##END WEBDEV

-  name: install pip libraries (pandas, numpy)
   become: yes
   become_user: root
   shell: pip3 install pandas numpy

-  name: create faex_gdax_importer.so link for web_ui
   shell: cd "{{faex_path}}"; ln -fs ../gdax/faex_gdax_importer.so web_ui/faex_gdax_importer.so


-  name: install nginx
   become: yes
   become_user: root
   apt:
      name: nginx
      update_cache: no

-  name: remove default nginx site
   become: yes
   become_user: root
   shell: rm -f /etc/nginx/sites-enabled/default

-  name: copy nginx conf
   become: yes
   become_user: root
   template: src=nginx_faex.conf dest=/etc/nginx/sites-available/faex.conf

-  name: enable nginx conf
   become: yes
   become_user: root
   shell: cd "/etc/nginx/"; ln -fs ../sites-available/faex.conf sites-enabled/

-  name: restart nginx
   become: yes
   become_user: root
   service: name=nginx state=restarted enabled=yes

